-- Helios Blog v2.0 - complete fresh database initialization
-- This is the single source of truth for the project database schema.
begin;

create extension if not exists pgcrypto;

do $$
begin
    create type public.post_level as enum ('beginner', 'intermediate', 'advanced');
exception
    when duplicate_object then null;
end
$$;

create table if not exists public.category (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null unique,
    icon text,
    description text not null,
    examples text not null default '',
    display_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    constraint category_name_length check (char_length(trim(name)) between 1 and 80),
    constraint category_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint category_slug_length check (char_length(slug) <= 100),
    constraint category_icon_length check (icon is null or char_length(trim(icon)) between 1 and 16),
    constraint category_description_length check (char_length(trim(description)) between 1 and 300),
    constraint category_examples_length check (char_length(examples) <= 500),
    constraint category_display_order_positive check (display_order >= 0)
);

insert into public.category (name, slug, icon, description, examples, display_order)
values
    ('Articles', 'articles', '📝', 'Các bài viết kiến thức chính', 'Docker, Kubernetes, FastAPI, Linux', 1),
    ('Projects', 'projects', '🚀', 'Giới thiệu các dự án', 'URL Shortener, Blog CMS, Monitoring Stack', 2),
    ('Series', 'series', '📖', 'Chuỗi bài viết', 'Learn Kubernetes, Build a SaaS, DevOps Roadmap', 3),
    ('Notes', 'notes', '📒', 'Ghi chú ngắn', 'Cheat sheet Git, Linux Commands', 4),
    ('Ideas', 'ideas', '💡', 'Ý tưởng', 'Startup Ideas, App Ideas', 5),
    ('Journeys', 'journeys', '🎯', 'Nhật ký học tập', '100 Days of Code, Internship Journey', 6),
    ('Snippets', 'snippets', '⚡', 'Code ngắn', 'Regex, SQL, Bash, TypeScript', 7),
    ('Reviews', 'reviews', '📚', 'Review sách, khóa học', 'Clean Architecture, Designing Data Intensive Applications', 8),
    ('Resources', 'resources', '🛠', 'Công cụ', 'VSCode Extensions, Docker Images', 9),
    ('Life', 'life', '🌏', 'Cuộc sống cá nhân', 'Gym, Productivity, Travel', 10),
    ('Gallery', 'gallery', '📷', 'Hình ảnh', 'Minecraft, Photography', 11),
    ('Changelog', 'changelog', '📰', 'Cập nhật blog', 'Version blog, thay đổi giao diện', 12)
on conflict (slug) do nothing;

create table if not exists public.series (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null unique,
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    constraint series_name_length check (char_length(trim(name)) between 1 and 100),
    constraint series_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint series_slug_length check (char_length(slug) <= 100),
    constraint series_description_length check (description is null or char_length(description) <= 500)
);

create table if not exists public.post (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    title text not null,
    description text not null,
    content text not null,
    image_url text,
    category text not null default 'articles' references public.category(slug) on update cascade on delete restrict,
    level public.post_level not null default 'beginner',
    reading_time smallint not null default 5,
    series_id bigint references public.series(id) on delete restrict,
    series_order smallint,
    published boolean not null default false,
    published_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    constraint post_title_length check (char_length(trim(title)) between 1 and 120),
    constraint post_description_length check (char_length(trim(description)) between 1 and 300),
    constraint post_content_length check (char_length(trim(content)) between 1 and 50000),
    constraint post_image_url_length check (image_url is null or char_length(image_url) <= 2048),
    constraint post_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint post_slug_length check (char_length(slug) <= 200),
    constraint post_reading_time_range check (reading_time between 1 and 120),
    constraint post_series_pair check ((series_id is null) = (series_order is null)),
    constraint post_series_order_positive check (series_order is null or series_order > 0),
    constraint post_series_order_unique unique (series_id, series_order),
    constraint post_publish_date check (published or published_at is null)
);

create table if not exists public.tag (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null unique,
    created_at timestamptz not null default now(),
    constraint tag_name_length check (char_length(trim(name)) between 1 and 80),
    constraint tag_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint tag_slug_length check (char_length(slug) <= 100)
);

create table if not exists public.post_tags (
    post_id bigint not null references public.post(id) on delete cascade,
    tag_id bigint not null references public.tag(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (post_id, tag_id)
);

create table if not exists public.site_settings (
    key text primary key,
    value jsonb not null,
    is_public boolean not null default false,
    updated_at timestamptz not null default now(),
    constraint site_settings_key_format check (key ~ '^[a-z][a-z0-9_]*$')
);

insert into public.site_settings (key, value, is_public)
values ('accent_color', to_jsonb('#1f51ff'::text), true)
on conflict (key) do nothing;

create index if not exists idx_post_publication
    on public.post (published, published_at desc, created_at desc);
create index if not exists idx_post_category
    on public.post (category);
create index if not exists idx_category_display_order
    on public.category (display_order, id);
create index if not exists idx_post_level
    on public.post (level);
create index if not exists idx_post_series
    on public.post (series_id, series_order)
    where series_id is not null;
create index if not exists idx_post_tags_tag_id
    on public.post_tags (tag_id, post_id);
create index if not exists idx_site_settings_public
    on public.site_settings (is_public)
    where is_public = true;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_post_updated_at on public.post;
create trigger set_post_updated_at
    before update on public.post
    for each row execute function public.set_updated_at();

drop trigger if exists set_category_updated_at on public.category;
create trigger set_category_updated_at
    before update on public.category
    for each row execute function public.set_updated_at();

drop trigger if exists set_series_updated_at on public.series;
create trigger set_series_updated_at
    before update on public.series
    for each row execute function public.set_updated_at();

drop trigger if exists set_site_settings_updated_at on public.site_settings;
create trigger set_site_settings_updated_at
    before update on public.site_settings
    for each row execute function public.set_updated_at();

alter table public.post enable row level security;
alter table public.category enable row level security;
alter table public.series enable row level security;
alter table public.tag enable row level security;
alter table public.post_tags enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "Published posts are public" on public.post;
create policy "Published posts are public"
    on public.post for select
    using (published = true);

drop policy if exists "Categories are public" on public.category;
create policy "Categories are public"
    on public.category for select
    using (true);

drop policy if exists "Series are public" on public.series;
create policy "Series are public"
    on public.series for select
    using (true);

drop policy if exists "Tags are public" on public.tag;
create policy "Tags are public"
    on public.tag for select
    using (true);

drop policy if exists "Published post tags are public" on public.post_tags;
create policy "Published post tags are public"
    on public.post_tags for select
    using (
        exists (
            select 1
            from public.post
            where post.id = post_tags.post_id
              and post.published = true
        )
    );

drop policy if exists "Public site settings are readable" on public.site_settings;
create policy "Public site settings are readable"
    on public.site_settings for select
    using (is_public = true);

grant usage on schema public to anon, authenticated;
grant select on public.post, public.category, public.series, public.tag, public.post_tags, public.site_settings to anon, authenticated;

commit;
